services:
  echoradio:
    image: echoradio:latest
    container_name: echoradio
    ports:
      - "8000:8000"   # Icecast
      - "8080:8080"   # Flask app
      - "5678:5678"  # debugger port
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1